name: Run Address Sanitizer

on:
  push:

jobs:
  run-asan:
    runs-on: ubuntu-22.04

    steps:
      - name: Check out repository
        uses: actions/checkout@v2 
        with:
          ref: 0cac73eb3875f6ecb6105e533218dba1868d04c9

      - name: Install dependencies for project
        run: | 
          sudo apt-get update
          sudo apt-get install -y build-essential libncurses-dev libelf-dev libelf1 bison flex libssl-dev bc make gcc git wget elfutils libasm1 libdw1
          
      - name: Build repository 
        run: make defconfig && make -j$(nproc)
          
      - name: Install Address Sanitizer dependencies
        run: sudo apt-get install -y clang-14 libclang-14-dev llvm-14 llvm-14-dev llvm-14-tools llvm-14-linker-tools
      
      - name: Run Google Address Sanitizer
        run: |
          #!/bin/bash

          files=$(find . -type f)
          failed_compilations=0
          successful_compilations=0
          TIMEOUT_DURATION=60

          for file in $files; do
              if [[ "$file" == *.c || "$file" == *.cpp ]]; then
                  include_dirs=$(find . -name '*.h' -exec dirname {} + | sort -u | sed 's/^/-I /')
                  clang -I "$include_dirs" -fsanitize=address -O1 -fno-omit-frame-pointer -fno-common -fsanitize-recover=address -g "$file" -o ./compiled.out > compilation.log 2>&1
                    if [ $? -eq 0 ]; then
                        timeout $TIMEOUT_DURATION ./compiled.out
                        exit_status=$?
                          if [ $exit_status -ne 0 ]; then
                              ((successful_compilations += 1))
                              cat compilation.log
                              echo "--------------------------------------------------"
                          else
                              ((failed_compilations += 1))
                          fi
                    else
                        ((failed_compilations += 1))
                    fi
                    rm -f ./compiled.out
              fi
          done

          echo "Address Sanitizer Failures: $failed_compilations"
          echo "Address Sanitizer Successes: $successful_compilations"
